### ISSUE TITLE
Bind events instead of adding event as a property

### ISSUE THREAD

**Issue by joostf** [rijkvanzanten/minor-wafs#6]
AddEventListener is prefered over onhashchange..

**Comment by rijkvanzanten** [comment]
I suppose you are referring to the `window.onload` statement at line 3 instead of the `hash change` listener? The `hashchange` event is already used by calling addEventListener. See line 19

```js
window.addEventListener('hashchange', () => sections.toggle(window.location.hash));
```

**Comment by joostf** [comment]
Did you push your latest commits?

**Comment by rijkvanzanten** [comment]
I'm referring to the `app.js` file found in [assignment5/static/app.js](https://github.com/rijkvanzanten/minor-wafs/blob/master/assignment5/static/app.js) from my latest commit a7a75ceaa483056e7345e79d3794c2a126fd93b4. In which file did you came across `window.onhashchange`?

**Comment by joostf** [comment]
Aha, yes I'm referring to window.onload ;-)
